apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/part-of: platform-sandbox
data:
  APP_NAME: "sample-app"
  APP_ENV: "sandbox"
  LOG_LEVEL: "info"
  DOWNSCALE_SCHEDULE: "Mon-Fri 19:00-08:00 UTC, Sat-Sun 00:00-24:00 UTC"
  UPSCALE_REPLICAS: "3"