apiVersion: v1
kind: ResourceQuota
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/part-of: platform-sandbox
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "20"
    services: "5"
    persistentvolumeclaims: "0"