package cmd

import (
	"fmt"
	"os/exec"
	"strings"

	"github.com/fatih/color"
	"github.com/spf13/cobra"
)

var costCmd = &cobra.Command{
	Use:     "cost",
	Short:   "Show cost savings report",
	Long:    `Displays the cost savings generated by the downscaler, pulled from the cost-reporter state.`,
	Example: `  platformctl cost`,
	RunE:    runCost,
}

func init() {
	rootCmd.AddCommand(costCmd)
}

func runCost(cmd *cobra.Command, args []string) error {
	color.Cyan("========================================")
	color.Cyan("     COST SAVINGS REPORT")
	color.Cyan("========================================")
	fmt.Println()

	// Get cost reporter state
	out, err := exec.Command("kubectl", "get", "configmap", "cost-reporter-state",
		"-n", namespace, "-o", "jsonpath={.data}").CombinedOutput()
	if err != nil {
		color.Yellow("No cost report data found yet.")
		fmt.Println("The cost reporter runs hourly. It may take some time to generate data.")
		fmt.Println()
		fmt.Println("Check cost-reporter CronJob status:")
		fmt.Println("  kubectl get cronjob cost-reporter -n", namespace)
		return nil
	}

	// Parse the data
	data := string(out)
	data = strings.Trim(data, "{}")
	pairs := strings.Split(data, " ")

	for _, pair := range pairs {
		pair = strings.TrimSpace(pair)
		if pair == "" {
			continue
		}
		kv := strings.SplitN(pair, ":", 2)
		if len(kv) != 2 {
			continue
		}
		key := strings.Trim(kv[0], "\"")
		val := strings.Trim(kv[1], "\"")

		switch key {
		case "downscaled_hours":
			color.Green("  Downscaled Hours:   %s", val)
		case "running_hours":
			color.Yellow("  Running Hours:      %s", val)
		case "total_savings":
			color.Green("  Total Savings:      $%s", val)
		case "last_report_date":
			if val != "" {
				fmt.Printf("  Last Report Date:   %s\n", val)
			}
		}
	}

	// Also show current replica count
	out, _ = exec.Command("kubectl", "get", "deployment", appName, "-n", namespace,
		"-o", "jsonpath={.spec.replicas}").CombinedOutput()
	fmt.Printf("  Current Replicas:   %s\n", string(out))

	fmt.Println()
	color.Cyan("========================================")
	return nil
}
