apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-downscaler
  namespace: kube-downscaler
  labels:
    app.kubernetes.io/name: kube-downscaler
    app.kubernetes.io/part-of: platform-sandbox